server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentDb
    username: root
    password: 260697
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888 #configuracion provisional

#Configuracion de Eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      deaultZone: http://localhost:8761/eureka